name: Test

on:
  push:

jobs:
  test:
    name: RSpec and Cucumber
    strategy:
      matrix:
        include:
          - ruby: 3.2
            gemfile: gemfiles/rails-6-1.gemfile
          - ruby: 3.2
            gemfile: gemfiles/rails-7-0.gemfile
          - ruby: 3.2
            gemfile: gemfiles/rails-7-1.gemfile
          - ruby: 3.3
            gemfile: gemfiles/rails-7-1.gemfile
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: carrierwave_test
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Cache gems
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles(matrix.gemfile) }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ matrix.ruby }}-
    - name: Setup ImageMagick policy
      run: sudo sh -c 'echo '\''<policymap><policy domain="coder" rights="read|write" pattern="PDF" /></policymap>'\'' > /etc/ImageMagick-6/policy.xml'
    - name: Update package list
      run: sudo apt update
    - name: Install ghostscript to process PDF
      run: sudo apt-get -y install ghostscript
    - name: Install libvips-dev for Carrierwave::Vips
      run: sudo apt-get install libvips-dev
    - name: Install dependencies
      run: bundle install --jobs=3 --retry=3 --path=vendor/bundle
    - name: Run RSpec
      run: bundle exec rake spec
    - name: Run Cucumber
      run: bundle exec rake features
